#!/usr/bin/env python3
"""Bake assets/generated/*.png into gen-assets.js as base64 data URIs.

gen-assets.js defines window.GEN_ASSETS = { "<name>": "data:image/png;base64,..." }.
app.js picks assets up from there and falls back to procedural textures when
a name is missing — so this file is safe to bake with zero assets.

Usage: python3 scripts/bake_assets.py
"""
import base64
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "generated"
OUT = ROOT / "gen-assets.js"

MIME = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".webp": "image/webp"}

assets = {}
if SRC.is_dir():
    for f in sorted(SRC.iterdir()):
        mime = MIME.get(f.suffix.lower())
        if not mime or f.name.endswith(".orig.png"):
            continue
        b64 = base64.b64encode(f.read_bytes()).decode()
        assets[f.stem] = f"data:{mime};base64,{b64}"
        print(f"baked {f.name} ({f.stat().st_size // 1024} KB)")

OUT.write_text(
    "/* generated by scripts/bake_assets.py — do not edit by hand */\n"
    f"window.GEN_ASSETS = {json.dumps(assets, ensure_ascii=False, indent=0)};\n",
    encoding="utf-8",
)
print(f"wrote {OUT.name} with {len(assets)} asset(s)")
if assets:
    print("next: python3 scripts/build.py")
